[bsp][ESP32_C3]增加ble和wifi驱动|add ble & wifi drivers
RT-Thread-packages/esp-idf pull request #11
Opened 2023-10-19 13:14 UTC by WCX1024979076

修改`SconsStruct`文件将`wifi`和`ble`组件加入编译中，并且修正了`include`路径问题，目前可以完成`wifi`和`ble`的编译但运行存在一些问题。本PR主要配合 https://github.com/RT-Thread/rt-thread/pull/8104 进行使用。

2023-10-19 23:23 UTC, supperthomas approved these changes

2023-10-19 23:26 UTC, supperthomas requested changes
建议将所有修改都用宏包起来，方便后续更新，宏尽量用同一种判断，比如#ifdef或者#ifndef，两个选一种，这样看起来比较方便。

2023-10-20 00:09 UTC, WCX1024979076 commented
> 建议将所有修改都用宏包起来，方便后续更新，宏尽量用同一种判断，比如#ifdef或者#ifndef，两个选一种，这样看起来比较方便。

好的

2023-10-20 00:33 UTC, WCX1024979076 commented
另一些代码只改动了.h路径，主要修正include重名问题，用之前的esp-idf编译工具同样能够编译，就不用宏定义包裹了

2023-10-20 04:35 UTC, supperthomas approved these changes

2023-10-22 15:31 UTC, merged